#!/bin/bash
MEMBERS=("junsuk")

WORKDIR="/home/workspace"
DATADIR="/home/data"

WORKDIR="/home/workspace"
DATADIR1="/home/brain_2d"
DATADIR2="/home/DecathlonDataset"
DATADIR3="/home/temp"
IMAGE_NAME="monai_brain_segmentation"
IMAGE_TAG="0.1"
CONTAINER_NAME="hw_ai4ch_brain_tumour_junsuk"
USER="junsuk"
GPUS='"device=4"'
PROJECT_REPO_DIR="/home/junsuk/project_brain_segmentation/code"
PROJECT_DATA_DIR1="/raid/junsuk/brain_segmentation/brain_2d"
PROJECT_DATA_DIR2="/raid/junsuk/brain_segmentation/DecathlonDataset"
PROJECT_DATA_DIR3="/raid/junsuk/brain_segmentation/junsuk_temp"
REMOVE_ON_END=true
